prefix sdo: <https://schema.org/>
prefix dbo: <http://dbpedia.org/ontology/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
construct {
  ?this a sdo:Thing ;
    sdo:additionalType <http://vocab.getty.edu/aat/300343602>;
    sdo:name ?name
} 
where {
  $this a/rdfs:subClassOf* dbo:Plant; rdfs:label ?name .
      filter(lang(?name) = 'nl')
} limit 10
