prefix sdo: <https://schema.org/>
prefix dbo: <http://dbpedia.org/ontology/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
construct {
  ?this rdfs:comment "This was generated using LDWorkbench";
} 
where {
  $this a dbo:Plant
}
