name: AO
stages:
  - name: "Events"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://static/ao/events-iterator.rq
    generator:
      - batchSize: 1000
        query: file://static/ao/events-generator.rq
  - name: "Makers"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://static/ao/makers-iterator.rq
    generator:
      - batchSize: 1000
        query: file://static/ao/makers-generator.rq
  - name: "ObjectDates"
    iterator:
      batchSize: 10000
      delay: 500ms
      #endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      #endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/services/virtuoso/sparql
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/services/jena/sparql
      query: file://static/ao/objectDates-iterator.rq
    generator:
      - batchSize: 1000
        query: file://static/ao/objectDates-generator.rq
  - name: "ObjectImages"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://static/ao/objectImages-iterator.rq
    generator:
      - batchSize: 1000
        query: file://static/ao/objectImages-generator.rq
  - name: "ObjectLocations"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://static/ao/objectLocations-iterator.rq
    generator:
      - batchSize: 1000
        query: file://static/ao/objectLocations-generator.rq
  - name: "ObjectLocationDates"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://static/ao/objectLocationDates-iterator.rq
    generator:
      - batchSize: 1000
        query: file://static/ao/objectLocationDates-generator.rq
  - name: "Objects"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://static/ao/objects-iterator.rq
    generator:
      - batchSize: 1000
        query: file://static/ao/objects-generator.rq
  - name: "Sites"
    iterator:
      batchSize: 10000
      delay: 500ms
      endpoint: https://api.demo.triplydb.com/datasets/projects/colonial-heritage/sparql
      query: file://static/ao/sites-iterator.rq
    generator:
      - batchSize: 1000
        query: file://static/ao/sites-generator.rq
