prefix aat:  <http://vocab.getty.edu/aat/>
prefix colonialHeritage: <https://test.triply.cc/colonialHeritage-test/graph/Sites(1).csv/def/>
prefix crm: <http://www.cidoc-crm.org/cidoc-crm/>
prefix dct: <http://purl.org/dc/terms/>
prefix la: <https://linked.art/ns/terms/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
construct {
  ?siteID a la:Set;
    crm:P2_has_type aat:300378926;
    rdfs:label ?siteName.
  #siteID
  ?siteID crm:P1_is_identified_by _:skolemNodeSiteID.
  _:skolemNodeSiteID a crm:E42_Identifier ;
    crm:P2_has_type aat:300404626 ;
    rdfs:label "Identification number";
    crm:P190_has_symbolic_content ?siteID.
  # "LocationNote"=EN
  ?siteID crm:P67i_is_referred_to_by _:skolemNodeLocationNodeEn.
  _:skolemNodeLocationNodeEn a crm:E33_Linguistic_Object ;
    crm:P2_has_type aat:300435416 ;
    rdfs:label "Description in English";
    # locationNotes could be HTML or string literal
    crm:P190_has_symbolic_content ?locationNotes;
    crm:P72_has_language aat:300388277.
  # "Environment"=NL
  ?siteID crm:P67i_is_referred_to_by _:skolemNodeEnvironment.
  _:skolemNodeEnvironment a crm:E33_Linguistic_Object;
    crm:P2_has_type aat:300435416;
    rdfs:label "Description in Dutch" ;
    crm:P190_has_symbolic_content ?environment;
    crm:P72_has_language aat:300411849.
  #  # "Description"=ID
  ?siteID crm:P67i_is_referred_to_by _:skolemNodeDesc.
  _:skolemNodeDesc a crm:E33_Linguistic_Object;
    crm:P2_has_type aat:300435416;
    rdfs:label "Description in Indonesian" ;
    crm:P190_has_symbolic_content ?description;
    crm:P72_has_language aat:300388460.
  # Remarks (should only be created when Remarks is not empty)
  ?siteID crm:P67i_is_referred_to_by ?skolemNodeRemarks.
  ?skolemNodeRemarks a crm:E33_Linguistic_Object;
    crm:P2_has_type aat:300435415;
    rdfs:label "Remarks" ;
    crm:P190_has_symbolic_content ?remarks.
  # Dimensions (should only be created when Dimensions is not empty)
  ?siteID crm:P67i_is_referred_to_by ?skolemNodeDimensions.
  ?skolemNodeDimensions a crm:E33_Linguistic_Object;
    crm:P2_has_type aat:300418049;
    rdfs:label "Temporal or spatial coverage" ;
    crm:P190_has_symbolic_content ?dimensions.
  # ResearcherComments
  ?siteID crm:P67i_is_referred_to_by _:skolemNodeResearcherComments.
  _:skolemNodeResearcherComments a crm:E33_Linguistic_Object;
    crm:P2_has_type aat:300435415;
    rdfs:label "Researcher comment" ;
    crm:P190_has_symbolic_content ?researcherComment.
  # IsPublic (should only be created when IsPublic is equal to "1")
  ?siteID dct:accessRights ?skolemNodeIsTrue.
  ?skolemNodeIsTrue a dct:RightsStatement;
    rdfs:label "Yes, for public use".
}
where {
  $this colonialHeritage:siteID ?siteID0.
  bind(iri(concat(str(<https://colonial-heritage.triply.cc/nmvw/id/site/>), ?siteID0)) as ?siteID).
  #siteName
  $this colonialHeritage:siteName ?siteName.
  # "LocationNote"=EN
  $this colonialHeritage:LocationNotes ?locationNotes.
  # "Environment"=NL
  $this colonialHeritage:Environment ?environment.
  # "Description"=ID
  $this colonialHeritage:Description ?description.
  # Dimensions (should only be created when Dimensions is not empty)
  $this colonialHeritage:Dimensions ?dimensions.
  optional {
    filter(?dimensions != "\r\n")
    bind(bnode() as ?skolemNodeDimensions).
  }
  # Remarks (should only be created when Remarks is not empty)
  $this colonialHeritage:Remarks ?remarks.
  optional {
    filter(?remarks != "\r\n")
    bind(bnode() as ?skolemNodeRemarks).
  }
  # ResearcherComments
  $this colonialHeritage:ResearcherComments ?researcherComment.
  # IsPublic (should only be created when IsPublic is equal to "1")
  $this colonialHeritage:IsPublic ?isPublic.
  optional {
    filter(?isPublic = "1")
    bind(bnode() as ?skolemNodeIsTrue).
  }
}