name: Test

on:
  pull_request:
    branches:
      - main

# cancel any ongoing job in the branch if there is one more recent
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event on ${{ github.ref }} - ${{ github.repository }}."
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check versions
        run: echo "Node version:" && node -v && echo "NPM version:" && npm -v
      - name: Install dependencies
        run: npm install
      - run: npm run lint
      - run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Build
        run: npm run compile
      - name: LDWorkbench init & test run
        run: rm -rf ./pipelines && npx ld-workbench --init && npx ld-workbench -c "test/utils/static/single/conf.yml"
      - name: Test
        run: npm run test
      - run: echo "Job status ${{ job.status }}."
